trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'finapp'  # Replace with your ACR connection name
    repository: 'finapp.azurecr.io/hello-world'  # Replace with your ACR name and desired image name
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: Docker@2
  displayName: 'Push Docker image to Azure Container Registry'
  inputs:
    containerRegistry: 'finapp'  # Replace with your ACR connection name
    repository: 'finapp.azurecr.io/hello-world'  # Replace with your ACR name and desired image name
    command: 'push'
    tags: |
      latest