# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Noode.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: Docker@2
  inputs:
    containerRegistry: 'deamon'
    repository: 'azure container registry'
    command: build
    Dockerfile: '**/Dockerfile'
  displayName: 'Docker image build'

- task: Docker@2
  inputs:
    containerRegistry: 'deamon'
    repository: 'Azure Container Registry'
    command: push
  displayName: 'Docker Image Push'